version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: davinci_app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src:cached
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge