version: '3.8'

services:
  mongodb-test:
    image: mongo:7.0
    container_name: mongodb-test
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123
      MONGO_INITDB_DATABASE: test_db
    ports:
      - "27018:27017"
    volumes:
      - mongodb_test_data:/data/db
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongodb_test_data:

networks:
  test-network:
    driver: bridge
