version: "3.9"

services:
  app_test:
    build: .
    container_name: davinci_app_test
    restart: "no"
    env_file:
      - .env.test
    depends_on:
      - postgres_test
    command: sh -c "npx prisma migrate deploy && npm test"

  postgres_test:
    image: postgres:15
    container_name: postgres_db_test
    restart: always
    ports:
      - "5433:5432" # Porta diferente da dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
